[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
test = "test"
solc = "0.8.22"
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@layerzerolabs/=node_modules/@layerzerolabs/",
    "forge-std/=lib/forge-std/src/",
]

[profile.default.fuzz]
runs = 256

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
